"""Seed data for the tracked-systems store: the 49 systems from
Red_ASAT_Systems.xlsx, mirrored verbatim from tactics_wiki.html's DATA
array (per data-layer: a delivered dataset's controlled values are
law - not re-canonicalised here). Used only to create the store if it
is genuinely absent; never re-applied over an existing, edited store."""

from typing import Any

# Literals repeated across records, named once so the catalogue stays a
# single source of truth (SonarQube python:S1192). Values are unchanged:
# seed data is mirrored verbatim from tactics_wiki.html.

ACTIVE_LEO_CLUSTER_ONGOING = (
    "Active LEO cluster, ongoing plane-change manoeuvres — highest currency"
)
CO_ORBITAL_INSPECTOR_KINETIC = "Co-orbital inspector + kinetic-kill vehicle, LEO"
DOGFIGHTING_PROFILE = "Dogfighting profile"
FOUR_HEAVENLY_KINGS = "Four Heavenly Kings"
GEO_SIGNALS_COLLECTION_CLUSTER = (
    "GEO signals-collection cluster with RPO and subsatellite release"
)
HIGHLY_MANOEUVRABLE_LEO_TRIADS = (
    "Highly manoeuvrable LEO triads, short operational life, subsatellite release"
)
LEO_DEPLOYMENT_CLUSTER_SUB = "LEO deployment cluster with sub-payload release"
LIT_15_YEARS = "<15 years"
LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP = (
    "2026 Manoeuvrable Cluster (Mothership / Volga R/B)"
)
LIT_2_3_YEARS = "2–3 years"
LIT_3_5_YEARS = "3–5 years"
LIT_4_YEARS = "4 years"
MANOEUVRABLE_MINOR_PLANE_PERIOD = "Manoeuvrable — minor plane/period changes"
NIVELIR_CLUSTER_1_2017 = "Nivelir Cluster 1 (2017)"
NIVELIR_CLUSTER_2_2019 = "Nivelir Cluster 2 (2019)"
NORAD_ID_CLASH_CROSS = "NORAD ID clash — cross-check UDL"
NUMIZMAT_NAVESKA_CLUSTER_2025 = "Numizmat / Naveska Cluster (2025)"
RELEASED_SUBSATELLITE = "Released subsatellite"
ROBOTIC_ARM_REFUELLING_CAPABLE = (
    "Robotic-arm and refuelling-capable GEO inspectors, highly manoeuvrable"
)
RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING = 'RPO, highly manoeuvrable "dogfighting".'
SHENLONG_REUSABLE_SPACEPLANE_RPO = "Shenlong — Reusable Spaceplane / RPO Testbed"
SHIJIAN_SJ_PROGRAMME_GEO = "Shijian (SJ) Programme — GEO Servicing / RPO"
SHIYAN_24C_32_LEO = 'Shiyan 24C / 32 — LEO "Dogfighting" RPO'
SIGNALS_COLLECTION = "Signals collection."
SUCCESSIVE_REUSABLE_SPACEPLANE_FLIGHTS = (
    "Successive reusable-spaceplane flights; RPO and payload recapture demonstrated"
)
TJS_FOUR_HEAVENLY_KINGS = 'TJS "Four Heavenly Kings" — Signals Collection'

SEED_RECORDS: list[dict[str, Any]] = [
    {
        "family_id": "rus-nivelir1",
        "family_title": NIVELIR_CLUSTER_1_2017,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "Nivelir #1",
        "catalogue_name": "COSMOS-2519",
        "launch_year": 2017,
        "launch_site": None,
        "norad_id": "42798",
        "regime": "LEO",
        "delta_v": None,
        "status": "decayed",
        "life": LIT_4_YEARS,
        "coplanar": None,
        "notes": "Mothership/inspector for the cluster.",
        "flag": None,
    },
    {
        "family_id": "rus-nivelir1",
        "family_title": NIVELIR_CLUSTER_1_2017,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "Daughter",
        "catalogue_name": "COSMOS-2521",
        "launch_year": 2017,
        "launch_site": None,
        "norad_id": "42919",
        "regime": "LEO",
        "delta_v": "340 m/s",
        "status": "decayed",
        "life": "2 years",
        "coplanar": None,
        "notes": "Deployed from Cosmos-2519.",
        "flag": None,
    },
    {
        "family_id": "rus-nivelir1",
        "family_title": NIVELIR_CLUSTER_1_2017,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "KKV",
        "catalogue_name": "COSMOS-2523",
        "launch_year": 2017,
        "launch_site": None,
        "norad_id": "42986",
        "regime": "LEO",
        "delta_v": "~27 m/s ejection",
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "Kinetic-kill vehicle ejected at ~27 m/s from Cosmos-2521.",
        "flag": None,
    },
    {
        "family_id": "rus-nivelir2",
        "family_title": NIVELIR_CLUSTER_2_2019,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "Nivelir #2",
        "catalogue_name": "COSMOS-2542",
        "launch_year": 2019,
        "launch_site": None,
        "norad_id": "44797",
        "regime": "LEO",
        "delta_v": None,
        "status": "decayed",
        "life": LIT_4_YEARS,
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-nivelir2",
        "family_title": NIVELIR_CLUSTER_2_2019,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "Daughter",
        "catalogue_name": "COSMOS-2543",
        "launch_year": 2019,
        "launch_site": None,
        "norad_id": "44835",
        "regime": "LEO",
        "delta_v": None,
        "status": "decayed",
        "life": "5 years",
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-nivelir2",
        "family_title": NIVELIR_CLUSTER_2_2019,
        "family_sub": CO_ORBITAL_INSPECTOR_KINETIC,
        "nation": "RU",
        "designator": "KKV",
        "catalogue_name": "Object E",
        "launch_year": 2019,
        "launch_site": None,
        "norad_id": "45915",
        "regime": "LEO",
        "delta_v": "140–186 m/s ejection",
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "Confirmed ASAT test: projectile ejected Jul 2020.",
        "flag": "ASAT test — confirmed",
    },
    {
        "family_id": "rus-nivelir3",
        "family_title": "Nivelir Cluster 3 (2022)",
        "family_sub": "Co-orbital inspector + daughter, LEO — decaying",
        "nation": "RU",
        "designator": "Nivelir #3",
        "catalogue_name": "COSMOS-2558",
        "launch_year": 2022,
        "launch_site": None,
        "norad_id": "53323",
        "regime": "LEO",
        "delta_v": None,
        "status": "decaying",
        "life": LIT_4_YEARS,
        "coplanar": None,
        "notes": "Decaying, currently ~350 km altitude.",
        "flag": None,
    },
    {
        "family_id": "rus-nivelir3",
        "family_title": "Nivelir Cluster 3 (2022)",
        "family_sub": "Co-orbital inspector + daughter, LEO — decaying",
        "nation": "RU",
        "designator": "Daughter",
        "catalogue_name": "Object C",
        "launch_year": 2022,
        "launch_site": None,
        "norad_id": "64627",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": "USA 326",
        "notes": "Blue coplanar object: USA 326.",
        "flag": None,
    },
    {
        "family_id": "rus-nivelir45",
        "family_title": "Nivelir #4 / #5 (2024–25)",
        "family_sub": "Standalone inspectors, LEO — active Blue coplanar shadowing",
        "nation": "RU",
        "designator": "Nivelir #4",
        "catalogue_name": "COSMOS-2576",
        "launch_year": 2024,
        "launch_site": None,
        "norad_id": "59773",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": "USA 314",
        "notes": "Blue coplanar object: USA 314.",
        "flag": "Blue coplanar",
    },
    {
        "family_id": "rus-nivelir45",
        "family_title": "Nivelir #4 / #5 (2024–25)",
        "family_sub": "Standalone inspectors, LEO — active Blue coplanar shadowing",
        "nation": "RU",
        "designator": "Nivelir #5",
        "catalogue_name": "COSMOS-2588",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "64095",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": "USA 338",
        "notes": "Blue coplanar object: USA 338.",
        "flag": "Blue coplanar",
    },
    {
        "family_id": "rus-egeo",
        "family_title": "eGEO Nivelir (2025)",
        "family_sub": "Extension of the Nivelir concept into GEO/HEO",
        "nation": "RU",
        "designator": "eGEO Nivelir",
        "catalogue_name": "COSMOS-2589",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "64467",
        "regime": "GEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "First GEO-regime Nivelir-pattern object.",
        "flag": None,
    },
    {
        "family_id": "rus-egeo",
        "family_title": "eGEO Nivelir (2025)",
        "family_sub": "Extension of the Nivelir concept into GEO/HEO",
        "nation": "RU",
        "designator": "eGEO Daughter",
        "catalogue_name": "COSMOS-2590",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "64527",
        "regime": "HEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "Deployed into HEO.",
        "flag": None,
    },
    {
        "family_id": "rus-numizmat",
        "family_title": NUMIZMAT_NAVESKA_CLUSTER_2025,
        "family_sub": LEO_DEPLOYMENT_CLUSTER_SUB,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2581",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "62902",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-numizmat",
        "family_title": NUMIZMAT_NAVESKA_CLUSTER_2025,
        "family_sub": LEO_DEPLOYMENT_CLUSTER_SUB,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2582",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "62903",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-numizmat",
        "family_title": NUMIZMAT_NAVESKA_CLUSTER_2025,
        "family_sub": LEO_DEPLOYMENT_CLUSTER_SUB,
        "nation": "RU",
        "designator": "Numizmat/Naveska",
        "catalogue_name": "COSMOS-2583",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "62904",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "Released Object F (NORAD 63330) on 18 Mar 2025.",
        "flag": None,
    },
    {
        "family_id": "rus-numizmat",
        "family_title": NUMIZMAT_NAVESKA_CLUSTER_2025,
        "family_sub": LEO_DEPLOYMENT_CLUSTER_SUB,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "Object F",
        "launch_year": 2025,
        "launch_site": None,
        "norad_id": "63330",
        "regime": "LEO",
        "delta_v": None,
        "status": "unknown",
        "life": None,
        "coplanar": None,
        "notes": "Released from Cosmos-2583, 18 Mar 2025.",
        "flag": None,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": "Mothership",
        "catalogue_name": "Volga R/B",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68756",
        "regime": "LEO",
        "delta_v": "1000 m/s",
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": "Mothership/rocket body for the 2026 cluster.",
        "flag": None,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2609",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68754",
        "regime": "LEO",
        "delta_v": "−0.14° inclination, 5 May 26",
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": "Inclination change recorded 5 May 2026.",
        "flag": None,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2610",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68758",
        "regime": "LEO",
        "delta_v": MANOEUVRABLE_MINOR_PLANE_PERIOD,
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2611",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68759",
        "regime": "LEO",
        "delta_v": MANOEUVRABLE_MINOR_PLANE_PERIOD,
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": None,
        "flag": None,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2612",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68762",
        "regime": "LEO",
        "delta_v": "Manoeuvrable — minor plane changes",
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": "NORAD ID as recorded in source; not yet cross-checked against UDL.",
        "flag": NORAD_ID_CLASH_CROSS,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2613",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68762",
        "regime": "LEO",
        "delta_v": "150 m/s, +0.8° inclination, 14 May 26",
        "status": "onorbit",
        "life": None,
        "coplanar": "ICEYE-X36, ICEYE-X37",
        "notes": "Coplanar with ICEYE-X36 and ICEYE-X37. NORAD ID as recorded in source; not yet cross-checked against UDL.",
        "flag": NORAD_ID_CLASH_CROSS,
    },
    {
        "family_id": "rus-2026",
        "family_title": LIT_2026_MANOEUVRABLE_CLUSTER_MOTHERSHIP,
        "family_sub": ACTIVE_LEO_CLUSTER_ONGOING,
        "nation": "RU",
        "designator": None,
        "catalogue_name": "COSMOS-2614",
        "launch_year": 2026,
        "launch_site": None,
        "norad_id": "68762",
        "regime": "LEO",
        "delta_v": MANOEUVRABLE_MINOR_PLANE_PERIOD,
        "status": "onorbit",
        "life": None,
        "coplanar": None,
        "notes": "NORAD ID as recorded in source; not yet cross-checked against UDL.",
        "flag": NORAD_ID_CLASH_CROSS,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-17",
        "catalogue_name": "SJ-17",
        "launch_year": 2016,
        "launch_site": "WSC",
        "norad_id": "41838",
        "regime": "GEO",
        "delta_v": None,
        "status": "decayed",
        "life": "9 years",
        "coplanar": None,
        "notes": "Robotic arm; highly manoeuvrable.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-21",
        "catalogue_name": "SJ-21",
        "launch_year": 2021,
        "launch_site": "XSC",
        "norad_id": "49330",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": "10–15 years",
        "coplanar": None,
        "notes": "Boosted Beidou-2 G2 out of the GEO belt; highly manoeuvrable; on-orbit refuelling test with SJ-23.",
        "flag": "Debris removal precedent",
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-23",
        "catalogue_name": "SJ-23",
        "launch_year": 2023,
        "launch_site": "WSC",
        "norad_id": "55131",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Acts more like the Chinese GSSAP analogue; RPO.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-25",
        "catalogue_name": "SJ-25",
        "launch_year": 2025,
        "launch_site": "XSC",
        "norad_id": "62485",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "On-orbit refuelling test with SJ-21.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-28",
        "catalogue_name": "SJ-28",
        "launch_year": 2025,
        "launch_site": "WSC",
        "norad_id": "66549",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Acts more like the Chinese GSSAP analogue; RPO.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-29A",
        "catalogue_name": "SJ-29A",
        "launch_year": 2025,
        "launch_site": "WSC",
        "norad_id": "67302",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Spatial target detection demo, GSSAP-analogue, co-orbital pair with SJ-29B.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-29B",
        "catalogue_name": "SJ-29B",
        "launch_year": 2025,
        "launch_site": "WSC",
        "norad_id": "67403",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Spatial target detection demo, GSSAP-analogue, co-orbital pair with SJ-29A.",
        "flag": None,
    },
    {
        "family_id": "chn-sj",
        "family_title": SHIJIAN_SJ_PROGRAMME_GEO,
        "family_sub": ROBOTIC_ARM_REFUELLING_CAPABLE,
        "nation": "CN",
        "designator": "SJ-31",
        "catalogue_name": "SJ-31",
        "launch_year": 2026,
        "launch_site": "XSC",
        "norad_id": "69570",
        "regime": "HEO",
        "delta_v": None,
        "status": "onorbit",
        "life": "5–7 years",
        "coplanar": None,
        "notes": "HEO/Molniya orbit; high-altitude surveillance role.",
        "flag": "Only HEO SJ object",
    },
    {
        "family_id": "chn-sy12",
        "family_title": "Shiyan-12 (SY-12) — GSSAP Analogue",
        "family_sub": "Paired GEO RPO inspectors",
        "nation": "CN",
        "designator": "SY-12 01",
        "catalogue_name": "SY-12 01",
        "launch_year": 2021,
        "launch_site": "WSC",
        "norad_id": "50321",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Acts like the Chinese GSSAP analogue; RPO.",
        "flag": None,
    },
    {
        "family_id": "chn-sy12",
        "family_title": "Shiyan-12 (SY-12) — GSSAP Analogue",
        "family_sub": "Paired GEO RPO inspectors",
        "nation": "CN",
        "designator": "SY-12 02",
        "catalogue_name": "SY-12 02",
        "launch_year": 2021,
        "launch_site": "WSC",
        "norad_id": "50322",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "Acts like the Chinese GSSAP analogue; RPO.",
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": "TJS-3",
        "catalogue_name": "TJS-3",
        "launch_year": 2018,
        "launch_site": "XSC",
        "norad_id": "43874",
        "regime": "GEO",
        "delta_v": "Released subsatellite for calibration",
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "RPO, signals collection.",
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": "TJS-10",
        "catalogue_name": "TJS-10",
        "launch_year": 2023,
        "launch_site": "WSC",
        "norad_id": "58204",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": "RPO, signals collection.",
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": FOUR_HEAVENLY_KINGS,
        "catalogue_name": "TJS-15",
        "launch_year": 2025,
        "launch_site": "XSC",
        "norad_id": "63157",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": SIGNALS_COLLECTION,
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": FOUR_HEAVENLY_KINGS,
        "catalogue_name": "TJS-16",
        "launch_year": 2025,
        "launch_site": "WSC",
        "norad_id": "63397",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": SIGNALS_COLLECTION,
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": FOUR_HEAVENLY_KINGS,
        "catalogue_name": "TJS-17",
        "launch_year": 2025,
        "launch_site": "XSC",
        "norad_id": "63524",
        "regime": "GEO",
        "delta_v": RELEASED_SUBSATELLITE,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": SIGNALS_COLLECTION,
        "flag": None,
    },
    {
        "family_id": "chn-tjs",
        "family_title": TJS_FOUR_HEAVENLY_KINGS,
        "family_sub": GEO_SIGNALS_COLLECTION_CLUSTER,
        "nation": "CN",
        "designator": FOUR_HEAVENLY_KINGS,
        "catalogue_name": "TJS-19",
        "launch_year": 2025,
        "launch_site": "XSC",
        "norad_id": "63924",
        "regime": "GEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_15_YEARS,
        "coplanar": None,
        "notes": SIGNALS_COLLECTION,
        "flag": None,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 24C-01",
        "catalogue_name": "SHIYAN 24C 01",
        "launch_year": 2023,
        "launch_site": "WSC",
        "norad_id": "58650",
        "regime": "LEO",
        "delta_v": RELEASED_SUBSATELLITE,
        "status": "onorbit",
        "life": LIT_3_5_YEARS,
        "coplanar": None,
        "notes": RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING,
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 24C-02",
        "catalogue_name": "SHIYAN 24C 02",
        "launch_year": 2023,
        "launch_site": "WSC",
        "norad_id": "58651",
        "regime": "LEO",
        "delta_v": RELEASED_SUBSATELLITE,
        "status": "onorbit",
        "life": LIT_3_5_YEARS,
        "coplanar": None,
        "notes": RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING,
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 24C-03",
        "catalogue_name": "SHIYAN 24C 03",
        "launch_year": 2023,
        "launch_site": "WSC",
        "norad_id": "58652",
        "regime": "LEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_3_5_YEARS,
        "coplanar": None,
        "notes": 'RPO, optics testing, highly manoeuvrable "dogfighting".',
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 32-01",
        "catalogue_name": "SHIYAN 32-01",
        "launch_year": 2025,
        "launch_site": "JSC",
        "norad_id": "66376",
        "regime": "LEO",
        "delta_v": RELEASED_SUBSATELLITE,
        "status": "onorbit",
        "life": LIT_2_3_YEARS,
        "coplanar": None,
        "notes": RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING,
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 32-02",
        "catalogue_name": "SHIYAN 32-02",
        "launch_year": 2025,
        "launch_site": "JSC",
        "norad_id": "66378",
        "regime": "LEO",
        "delta_v": RELEASED_SUBSATELLITE,
        "status": "onorbit",
        "life": LIT_2_3_YEARS,
        "coplanar": None,
        "notes": RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING,
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-dogfight",
        "family_title": SHIYAN_24C_32_LEO,
        "family_sub": HIGHLY_MANOEUVRABLE_LEO_TRIADS,
        "nation": "CN",
        "designator": "SHIYAN 32-03",
        "catalogue_name": "SHIYAN 32-03",
        "launch_year": 2025,
        "launch_site": "JSC",
        "norad_id": "66379",
        "regime": "LEO",
        "delta_v": None,
        "status": "onorbit",
        "life": LIT_2_3_YEARS,
        "coplanar": None,
        "notes": RPO_HIGHLY_MANOEUVRABLE_DOGFIGHTING,
        "flag": DOGFIGHTING_PROFILE,
    },
    {
        "family_id": "chn-shenlong",
        "family_title": SHENLONG_REUSABLE_SPACEPLANE_RPO,
        "family_sub": SUCCESSIVE_REUSABLE_SPACEPLANE_FLIGHTS,
        "nation": "CN",
        "designator": "Shenlong-1",
        "catalogue_name": "PRC Test Spacecraft",
        "launch_year": 2020,
        "launch_site": "JSC",
        "norad_id": "46389",
        "regime": "LEO",
        "delta_v": None,
        "status": "decayed",
        "life": "2 days",
        "coplanar": None,
        "notes": "Multi-use RPO: servicing, repair, deployment, potential reconnaissance/ASAT test.",
        "flag": None,
    },
    {
        "family_id": "chn-shenlong",
        "family_title": SHENLONG_REUSABLE_SPACEPLANE_RPO,
        "family_sub": SUCCESSIVE_REUSABLE_SPACEPLANE_FLIGHTS,
        "nation": "CN",
        "designator": "Shenlong-2",
        "catalogue_name": "PRC Test Spacecraft 2",
        "launch_year": 2022,
        "launch_site": "JSC",
        "norad_id": "53357",
        "regime": "LEO",
        "delta_v": None,
        "status": "decayed",
        "life": "9 months",
        "coplanar": None,
        "notes": "Multi-use RPO: servicing, repair, deployment, potential reconnaissance/ASAT test.",
        "flag": None,
    },
    {
        "family_id": "chn-shenlong",
        "family_title": SHENLONG_REUSABLE_SPACEPLANE_RPO,
        "family_sub": SUCCESSIVE_REUSABLE_SPACEPLANE_FLIGHTS,
        "nation": "CN",
        "designator": "Shenlong-3",
        "catalogue_name": "PRC Test Spacecraft 3",
        "launch_year": 2023,
        "launch_site": "JSC",
        "norad_id": "58573",
        "regime": "LEO",
        "delta_v": "Payload released and recaptured",
        "status": "decayed",
        "life": "9 months",
        "coplanar": None,
        "notes": "Multi-use RPO: servicing, repair, deployment, potential reconnaissance/ASAT test. Payload sub-object also deorbited.",
        "flag": "Release + recapture demonstrated",
    },
    {
        "family_id": "chn-shenlong",
        "family_title": SHENLONG_REUSABLE_SPACEPLANE_RPO,
        "family_sub": SUCCESSIVE_REUSABLE_SPACEPLANE_FLIGHTS,
        "nation": "CN",
        "designator": "Shenlong-4",
        "catalogue_name": "PRC Test Spacecraft 4",
        "launch_year": 2026,
        "launch_site": "JSC",
        "norad_id": "67689",
        "regime": "LEO",
        "delta_v": None,
        "status": "onorbit",
        "life": "On-orbit since Feb 2026 (launched 7 Feb 2026)",
        "coplanar": None,
        "notes": 'Multi-use RPO: servicing, repair, deployment, potential reconnaissance/ASAT test. Payload "Object H" released and recaptured.',
        "flag": "Currently on-orbit — highest currency",
    },
]
